version: '3'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URL=mongodb://mongodb/amazona  # Update MongoDB URL to use the service name 'mongodb'
      - JWT_SECRET=somethingsecret
      - PAYPAL_CLIENT_ID=sb
      - accessKeyId=your_access_key_id
      - secretAccessKey=your_secret_access_key
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
