# Use a specific Node.js version
FROM node:14.18.1-alpine AS build

WORKDIR /app
COPY package*.json .
COPY . .

WORKDIR /app/backend
RUN npm install

EXPOSE 5000

# Start the application
CMD ["npm", "start"]
