version: '3.8'
services:
  frontend:
    image: catalingbr/ecommerce-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://127.0.0.1:5000

  backend:
    image: catalingbr/ecommerce-backend:latest
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URL=mongodb://mongodb/amazona  # Update MongoDB URL to use the service name 'mongodb'
      - JWT_SECRET=somethingsecret
      - PAYPAL_CLIENT_ID=sb
      - accessKeyId=your_access_key_id
      - secretAccessKey=your_secret_access_key
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
